replication:
  connections:
    - type: postgresql
      uri: postgresql://postgres:postgres@postgres:5432/postgres
      sslmode: disable

storage:
  type: postgresql
  uri: postgresql://postgres:postgres@postgres:5432/powersync_storage
  sslmode: disable

port: 8080

sync_config:
  path: sync-config.yaml

client_auth:
  jwks_uri: http://api:8000/.well-known/jwks.json
  block_local_jwks: false
  audience:
    - http://sync.localhost
    - http://localhost:8080
    - http://127.0.0.1:8080
  cors:
    allowed_origins:
      - http://app.localhost
